rule ARGOS_Mimikatz_Log_Output
{
    meta:
        description = "Detects log files generated by mimikatz credential dump output - T1003.001"
        author = "ARGOS SOC - Miguel Reguero"
        date = "2026-08-20"
        reference = "ESC21/ESC22 - ARGOS TFM - T1003.001"
        mitre = "T1003.001"
        score = 90
    strings:
        $log_auth     = "Authentication Id :" ascii wide
        $log_session  = "Session           :" ascii wide
        $log_password = "* Password :" ascii wide
        $log_ntlm     = "* NTLM     :" ascii wide
        $log_mimikatz = "mimikatz" ascii wide nocase
    condition:
        filesize < 50MB
        and (
            ($log_auth and $log_session and 1 of ($log_password, $log_ntlm))
            or
            ($log_mimikatz and 1 of ($log_auth, $log_password, $log_ntlm))
        )
}
