rule ARGOS_Certutil_Base64_Encoded_File
{
    meta:
        description = "Detects Base64 encoded files generated by certutil -encode - T1041"
        author = "ARGOS SOC - Miguel Reguero"
        date = "2026-08-20"
        reference = "ESC20 - ARGOS TFM - T1041"
        mitre = "T1041"
        score = 75
    strings:
        $cert_header = "-----BEGIN CERTIFICATE-----" ascii wide
        $cert_footer = "-----END CERTIFICATE-----" ascii wide
    condition:
        filesize < 50MB
        and $cert_header
        and $cert_footer
}
