include "/opt/argos/yara/rules/linux/argos_bash_reverse_shell.yar"
include "/opt/argos/yara/rules/linux/argos_bash_crontab_persistence.yar"
include "/opt/argos/yara/rules/linux/argos_ingress_tool_transfer_linux.yar"
include "/opt/argos/yara/rules/linux/argos_reverse_shell_interpreted.yar"
include "/opt/argos/yara/rules/linux/argos_webshell_linux.yar"
